name: kllpro

on:
  workflow_dispatch:
  schedule:
      - cron: '10 */3 * * *'
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 300
    if: github.event.repository.owner.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install md5-node
          npm install
      - name: '运行 【kllpro】'
        run: | 
          node Task/kllpro.js

    env:
          DFH: ${{ secrets.DFH }}
          DFHnum: ${{ secrets.DFHnum1 }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_KEY: ${{ secrets.PUSH_KEY2 }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
