name: wxyd

on:
  workflow_dispatch:
  schedule:
      - cron: '10 */2 * * *'
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60
    if: github.event.repository.owner.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install md5-node
          npm install
      - name: '运行 【wxyd】'
        run: | 
          node Task/wxyd.js
