name: wxyd

on:
  workflow_dispatch:
  schedule:
      - cron: '10 */2 * * *'
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60
    if: github.event.repository.owner.id
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install md5-node
          npm install
      - name: '运行 【wxyd】'
        run: | 
          curl --silent --location --request GET 'https://cip.cc/'
          node Task/wxyd.js

    env:
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_KEY: ${{ secrets.PUSH_KEY2 }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
